/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sams.view;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import sams.controller.ProgramController;
import sams.dto.ProgramDetailsDto;
import java.util.ArrayList;

/**
 *
 * @author kithruV
 */
public class Searchprogram extends JFrame {

    private ProgramController programController = new ProgramController();
    /**
     * Creates new form Searchprogram
     */
    public Searchprogram() {
        initComponents();
        loadTable();

        String searchText = programName.getText().trim();

        try {
            ArrayList<ProgramDetailsDto> programList = programController.getAllProgram();

            DefaultTableModel model = (DefaultTableModel) programTable.getModel();
            model.setRowCount(0);

            for (ProgramDetailsDto dto : programList) {
                // safely handle nulls
                String name = dto.getProgramName() != null ? dto.getProgramName().toLowerCase() : "";
                String code = dto.getProgramCode() != null ? dto.getProgramCode().toLowerCase() : "";

                if (name.contains(searchText.toLowerCase()) || code.contains(searchText.toLowerCase())) {
                    model.addRow(new Object[]{
                            dto.getProgramName(),
                            dto.getProgramCode(),
                            dto.getDuration(),
                            dto.getDescription(),
                            "Edit/Delete"
                    });
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Search failed: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        programIdForSearch = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        programName = new java.awt.TextField();
        searchProgramBtn = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        programTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        programIdForSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        programIdForSearch.setForeground(new java.awt.Color(51, 51, 255));
        programIdForSearch.setText("Search Program Details");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Program ID");

        searchProgramBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchProgramBtn.setText("Search");
        searchProgramBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProgramBtnActionPerformed(evt);
            }
        });

        programTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Program Name", "Program Code", "Duration", "Description", "Manage"
            }
        ));
        jScrollPane1.setViewportView(programTable);
        programTable.setColumnModel(Program Name);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel3)
                .addGap(65, 65, 65)
                .addComponent(programName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchProgramBtn)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(programIdForSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(programIdForSearch)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchProgramBtn)
                    .addComponent(jLabel3)
                    .addComponent(programName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchProgramBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProgramBtnActionPerformed
        searchProgramBtn.addActionListener(e -> searchPrograms());
    }//GEN-LAST:event_searchProgramBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Searchprogram.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Searchprogram.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Searchprogram.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Searchprogram.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Searchprogram().setVisible(true);
            }


        });
    }

    private void loadTable() {
        try {
            ArrayList<ProgramDetailsDto> programList = programController.getAllProgram();

            DefaultTableModel model = (DefaultTableModel) programTable.getModel();
            model.setRowCount(0); // clear old rows

            for (ProgramDetailsDto dto : programList) {
                model.addRow(new Object[]{
                        dto.getProgramName(),
                        dto.getProgramCode(),
                        dto.getDuration(),
                        dto.getDescription(),
                        "Edit/Delete"  // later replaced with buttons
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading programs: " + e.getMessage());
        }
    }
    private void searchPrograms() {
        String searchText = programName.getText().trim().toLowerCase();

        try {
            ArrayList<ProgramDetailsDto> programList = programController.getAllProgram();
            DefaultTableModel model = (DefaultTableModel) programTable.getModel();
            model.setRowCount(0);

            for (ProgramDetailsDto dto : programList) {
                String name = dto.getProgramName() != null ? dto.getProgramName().toLowerCase() : "";
                String code = dto.getProgramCode() != null ? dto.getProgramCode().toLowerCase() : "";

                if (name.contains(searchText) || code.contains(searchText)) {
                    model.addRow(new Object[]{
                            dto.getProgramName(),
                            dto.getProgramCode(),
                            dto.getDuration(),
                            dto.getDescription(),
                            "Edit/Delete"
                    });
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Search failed: " + e.getMessage());
        }
    }
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel programIdForSearch;
    private java.awt.TextField programName;
    private javax.swing.JTable programTable;
    private javax.swing.JToggleButton searchProgramBtn;
    // End of variables declaration//GEN-END:variables
}
